[book]
authors = ["PJ568", "WeDot-docs contributors", "Godot-docs contributors"]
language = "zh"
multilingual = true
src = "src"
title = "WeDot 引擎文档"
description = "WeDot 引擎文档旨在为开发者提供全面的指南和参考，帮助理解和使用 WeDot 引擎的各项功能。文档涵盖了从基础概念到高级特性的详细说明，包括但不限于 API 介绍、配置选项、最佳实践以及常见问题解答。"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
mathjax-support = false

# 文档起始位置：在编译前应设置为 branch 名称。
site-url = "{site.url}"
# site-url = "latest"

# 引入自定义功能和样式
additional-css = ["assets/override.css"]
additional-js = ["assets/override.js"]

# GitHub 链接
git-repository-url = "https://github.com/Wedot-Engine/WeDot-docs/"
edit-url-template = "https://github.com/Wedot-Engine/WeDot-docs/blob/latest/{path}"

[output.html.fold]
enable = true
level = 0

[output.html.playground]
copyable = true

[preprocessor.index]

[preprocessor.links]

[output.html.search]
heading-split-level = 0  # 将结果链接到标题级别，默认 3
teaser-word-count = 20   # 用于搜索结果摘要的字数，默认 30
limit-results = 15       # 最大搜索结果数，默认 30